name: Terraform CI/CD

on:
  push:
    branches: [ none ]
  pull_request:
    branches: [ none ]
  workflow_dispatch:

env:
  AWS_REGION: 'us-east-1'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: Prepare Lambda package
        run: |
          cd lambda
          zip -r lambda_function.zip handler.py
          cd ..

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Run Checkov (Security Scan)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
        continue-on-error: true

      - name: Run Trivy (Vulnerability Scan)
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          path: .
        continue-on-error: true
